### ISSUE TITLE
Can not load html from String

### ISSUE THREAD

**Issue by hiepvn** [shah-xad/webview_flutter_plus#20]
After upgrade to lastese verion, load html from String is not working.
Can anyone please help me out with this?

Thanks in advance.

```
// pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_plus: ^0.2.1+1
```

```
// WebViewPage.dart

class WebViewPage extends StatefulWidget {
  WebViewPage({Key? key}) : super(key: key);

  @override
  _WebViewPageState createState() => _WebViewPageState();
}


class _WebViewPageState extends State<WebViewPage> {

  @override void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("WebViewPlus"),
      ),
      body: WebViewPlus(
        javascriptMode: JavascriptMode.unrestricted,
        onWebViewCreated: (controller) {
          controller.loadString(r"""
            <html lang="en">
              <body>hello world</body>
            </html>"""
          );
        },
      ),
    );
  }
}
```

![Screen Shot 2021-05-22 at 13 13 50](https://user-images.githubusercontent.com/2033402/119214158-8ffbc200-baff-11eb-9948-410d4000cc69.png)

**Comment by naizapp** [comment]
Same here. Did you got any solution yet ?

**Comment by shah-xad** [comment]
Please use like this:

```
controller.loadString(r"""
           <html lang="en">
            <body>hello world</body>
           </html>
      """, mimeType: 'text/html');
```
Add this argument `mimeType: 'text/html'`, rest is OK I'll put it by default in the next release.

**Comment by shah-xad** [comment]
Hi, I'm sorry but I have to restart this package as I found some issue with webview_flutter. Now, `webview_flutter_plus` is much improved than its previous versions. Please give it a try now. And check if your issue persists is webview_flutter then it'll also be here because it's just an extension of that.
