### ISSUE TITLE
flutter: Error: Unable to load asset: assets/index.caf8b167.css

### ISSUE THREAD

**Issue by ColtonBristow** [shah-xad/webview_flutter_plus#31]
https://gyazo.com/8223832b4d5845d2db17dd4d07e2e742

I am unable to load associated CSS files from index.HTML

**Comment by shah-xad** [comment]
have you added them in your pubspec.yaml?

**Comment by shah-xad** [comment]
and I didn't see any file with the name  `index.caf8b167.cs` in your assets.

**Comment by ColtonBristow** [comment]
yes it was added to the pubspec

**Comment by shah-xad** [comment]
can you share reproduceable example regarding your code?

**Comment by ColtonBristow** [comment]
Here is the repo https://github.com/ColtonBristow/newflutterthree . all I did was build a three js web app and tried to use it through referencing the HTML file.

**Comment by ColtonBristow** [comment]
`class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Help'),
        ),
        body: WebViewPlus(
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (controller) {
            final int? port = controller.serverPort;
            controller.loadUrl('EmbeddedThreeJS/dist/index.html');
          },
        ),
      ),
    );
  }
}`

**Comment by ColtonBristow** [comment]
` class MyApp extends StatelessWidget {
  MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Help'),
        ),
        body: WebViewPlus(
          javascriptMode: JavascriptMode.unrestricted,
          onWebViewCreated: (controller) {
            final int? port = controller.serverPort;
            controller.loadUrl('EmbeddedThreeJS/dist/index.html');
          },
        ),
      ),
    );
  }
} `

**Comment by shah-xad** [comment]
I think there's some conflict between your assets directory and pubspec.yaml. You haven't added them correctly in your yaml file. There's no `dist` directory in actual but you mentioned that in your code here:       `controller.loadUrl('EmbeddedThreeJS/dist/index.html');`

**Comment by ColtonBristow** [comment]
```
assets:
    - EmbeddedThreeJS/
    - EmbeddedThreeJS/dist/
    - EmbeddedThreeJS/dist/assets/
    - EmbeddedThreeJS/dist/index.html

```

**Comment by shah-xad** [comment]
There're plenty of problems in your project, pubspec.yaml, main.dart, android manifest your HTML content, even you didn't follow the instructions for the library, Here's your fixed code but please do get familiar with the basics.

[fixed.zip](https://github.com/shah-xad/webview_flutter_plus/files/8163974/fixed.zip)

**Comment by ColtonBristow** [comment]
could you tell me what exactly was wrong? and I did follow all the documentation that you posted as far as I know. So some feedback on how you fixed it would be great!

**Comment by shah-xad** [comment]
You hadn't added the required permissions in your android manifest.  There's no directory named dist and in your pubspec you're using this. In your index.html there's also path problem.
