### ISSUE TITLE
localstorage does not work since http server starts on different port each time

### ISSUE THREAD

**Issue by whollacsek** [shah-xad/webview_flutter_plus#32]

**Comment by shah-xad** [comment]
Need details, this isn't enough to understand your issue.

**Comment by whollacsek** [comment]
Hi Shah-Xad I have a web app bundled in the assets folder that I load
through initialUrl, this webview library starts a http server to serve the
static files however because the http server starts on a different port
each time the webview is loaded some browser API relying on the url doesn't
work. In my case localstorage is not working because each url is considered
a different website

**Comment by shah-xad** [comment]
What I understood is you're using a static port number in your web files, right? I'd suggest you load local files in the browser from getting URL like this `var currentUrl = location.protocol + '//' + location.host + '/';`.

**Comment by whollacsek** [comment]
No I'm not using a static port, the http server implemented in this library
assigns a random port which means each time the webview is loaded with
assets files it is considered as a different website so localstorage is
saving and loading from different domain thus data is lost

**Comment by shah-xad** [comment]
Your problem has been resolved, please consider the latest version: `0.3.0+2`. From this version, now you can pass your own custom port, check the example.

**Comment by whollacsek** [comment]
Thanks @shah-xad for your help!

**Comment by shah-xad** [comment]
Sorry, I accidentally closed the issue, you didn't tell me if the issue is resolved?
